---
- name: Check if initialization has been done
  stat: path={{ ansible_env.HOME }}/.initialized
  register: initialized

- name: First time apt-upgrade
  apt:
    update_cache: yes
    upgrade: "yes"
  become: true
  when: not initialized.stat.exists

- include: hosts.yml
- include: lockdown_sshd.yml
- include: firewall.yml

- name: Create /root/.initialized lock file
  file:
    path: "{{ ansible_env.HOME }}/.initialized"
    state: touch
  become: true
  when: not initialized.stat.exists